# Generated by Django 5.2.5 on 2025-09-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_user_is_approved"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("company_type", models.CharField(max_length=100)),
                ("major_activity", models.CharField(max_length=255)),
                ("nature_of_business", models.CharField(max_length=255)),
                ("services_or_products", models.TextField()),
                ("company_address", models.TextField()),
                ("gstin_no", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "gst_certificate",
                    models.FileField(
                        blank=True, null=True, upload_to="certificates/gst/"
                    ),
                ),
                ("msme_no", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "msme_certificate",
                    models.FileField(
                        blank=True, null=True, upload_to="certificates/msme/"
                    ),
                ),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "enterprise_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "bank_certificate",
                    models.FileField(
                        blank=True, null=True, upload_to="certificates/bank/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
