# Generated by Django 5.2.5 on 2025-09-02 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_company_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="services_or_products",
        ),
        migrations.AddField(
            model_name="company",
            name="account_holder_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="cancel_cheque",
            field=models.FileField(
                blank=True, null=True, upload_to="certificates/cancel_cheque/"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="ifsc_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="company_type",
            field=models.CharField(
                choices=[
                    ("PVT_LTD", "Pvt. Ltd."),
                    ("PROPRIETORSHIP", "Proprietorship"),
                    ("LLP", "LLP"),
                    ("GOV", "Gov. Company"),
                    ("OTHERS", "Others"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="enterprise_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MICRO", "Micro"),
                    ("SMALL", "Small"),
                    ("MEDIUM", "Medium"),
                    ("OTHERS", "Others"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="major_activity",
            field=models.CharField(
                choices=[
                    ("MANUFACTURER", "Manufacturer"),
                    ("SERVICES", "Services"),
                    ("RESALER", "Resaler"),
                    ("TRADER", "Trader"),
                    ("OTHERS", "Others"),
                ],
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="CompanyDirector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="directors",
                        to="app.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceOrProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services_products",
                        to="app.company",
                    ),
                ),
            ],
        ),
    ]
