# Generated by Django 5.2.5 on 2025-09-03 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_remove_company_services_or_products_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="bank_certificate",
        ),
        migrations.RemoveField(
            model_name="company",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="company",
            name="user",
        ),
        migrations.AddField(
            model_name="company",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="bank_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="account_holder_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="cancel_cheque",
            field=models.FileField(
                blank=True, null=True, upload_to="company_docs/cheques/"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="company_type",
            field=models.CharField(
                choices=[
                    ("PVT_LTD", "Pvt. Ltd."),
                    ("LLP", "LLP"),
                    ("PARTNERSHIP", "Partnership"),
                    ("PROPRIETORSHIP", "Proprietorship"),
                    ("ENTERPRISES", "Enterprises"),
                    ("OTHER", "Other"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="enterprise_type",
            field=models.CharField(
                blank=True,
                choices=[("MICRO", "Micro"), ("SMALL", "Small"), ("MEDIUM", "Medium")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="gst_certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="company_docs/gst/"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="major_activity",
            field=models.CharField(
                choices=[
                    ("MANUFACTURE", "Manufacture"),
                    ("SERVICES", "Services"),
                    ("TRADER", "Trader"),
                    ("RESELLER", "Reseller"),
                    ("OTHER", "Other"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="msme_certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="company_docs/msme/"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="msme_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="nature_of_business",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="companydirector",
            name="phone",
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name="CompanyMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="app.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanyOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owners",
                        to="app.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanyPartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partners",
                        to="app.company",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ServiceOrProduct",
        ),
    ]
