# Generated by Django 5.2.6 on 2025-11-05 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_bid_alter_company_created_by_aidocumenttask_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aidocumenttask",
            name="company",
        ),
        migrations.RemoveField(
            model_name="aidocumenttask",
            name="document",
        ),
        migrations.RemoveField(
            model_name="aidocumenttask",
            name="user",
        ),
        migrations.RemoveField(
            model_name="generateddocument",
            name="task",
        ),
        migrations.RemoveField(
            model_name="tenderrequirement",
            name="task",
        ),
        migrations.DeleteModel(
            name="Bid",
        ),
        migrations.DeleteModel(
            name="GeneratedDocument",
        ),
        migrations.DeleteModel(
            name="AIDocumentTask",
        ),
        migrations.DeleteModel(
            name="TenderRequirement",
        ),
    ]
