# Generated by Django 5.2.6 on 2025-11-06 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_remove_aidocumenttask_company_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequiredDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("PAN", "PAN Card"),
                            ("INC_CERT", "Incorporation Certificate"),
                            ("AADHAAR", "Aadhaar Card"),
                            ("UDYAM", "Udyam Certificate"),
                            ("GST_CERT", "GST Certificate"),
                            ("BANK_PROOF", "Bank Proof"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("document_name", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="company_docs/required/"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="required_docs",
                        to="app.company",
                    ),
                ),
            ],
        ),
    ]
