# Generated by Django 5.2.6 on 2025-11-08 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_requireddocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadedCompanyDocuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_file", models.FileField(upload_to="read_docs/originals/")),
                ("filename", models.CharField(blank=True, max_length=512)),
                ("content_type", models.CharField(blank=True, max_length=128)),
                ("extracted_text_raw", models.TextField(blank=True, null=True)),
                ("extracted_text_clean", models.TextField(blank=True, null=True)),
                ("model_used", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "ai_provider",
                    models.CharField(blank=True, default="huggingface", max_length=100),
                ),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("tokens_used", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_documents",
                        to="app.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "required_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_read_results",
                        to="app.requireddocument",
                    ),
                ),
            ],
        ),
    ]
