# Generated by Django 5.2.6 on 2025-11-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_readedcompanydocuments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="readedcompanydocuments",
            name="ai_provider",
        ),
        migrations.RemoveField(
            model_name="readedcompanydocuments",
            name="confidence_score",
        ),
        migrations.RemoveField(
            model_name="readedcompanydocuments",
            name="required_document",
        ),
        migrations.RemoveField(
            model_name="readedcompanydocuments",
            name="tokens_used",
        ),
        migrations.AddField(
            model_name="company",
            name="audited_balance_sheet",
            field=models.FileField(
                blank=True, null=True, upload_to="company_docs/balance_sheet/"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="bidder_turnover_certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="company_docs/turnover/bidder/"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="eft_mandate",
            field=models.FileField(
                blank=True, null=True, upload_to="company_docs/eft/"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="epf_registration",
            field=models.FileField(
                blank=True, null=True, upload_to="company_docs/epf/"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="esic_registration",
            field=models.FileField(
                blank=True, null=True, upload_to="company_docs/esic/"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="factory_license",
            field=models.FileField(
                blank=True, null=True, upload_to="company_docs/factory/"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="incorporation_certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="company_docs/incorp/"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="networth_certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="company_docs/networth/"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="oem_turnover_certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="company_docs/turnover/oem/"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="pan_card",
            field=models.FileField(
                blank=True, null=True, upload_to="company_docs/pan/"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="product_catalog",
            field=models.FileField(
                blank=True, null=True, upload_to="company_docs/catalog/"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="purchase_document",
            field=models.FileField(
                blank=True, null=True, upload_to="company_docs/purchase/"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="quality_certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="company_docs/quality/"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="undertaking_blacklisting",
            field=models.FileField(
                blank=True, null=True, upload_to="company_docs/undertaking/"
            ),
        ),
    ]
