# Generated by Django 5.2.6 on 2025-11-14 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_remove_readedcompanydocuments_ai_provider_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtractedTextDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_file", models.FileField(upload_to="extracted_docs/")),
                ("extracted_text", models.TextField(blank=True)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.company",
                    ),
                ),
            ],
        ),
    ]
