# Generated by Django 5.2.6 on 2025-12-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_extractedtextdocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="annual_turnover",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="designation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="years_of_experience",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
